name: go test
on: [ push, pull_request ]

jobs:
  go-test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=1m
          skip-cache: false

      - name: Test
        run: go test -v -race ./...
